baseURL = 'https://noahrod.github.io/thenoahnoah/'
canonifyURLs = true
languageCode = 'en-us'
title = 'The Noah Noah'
theme = "fairy-hugo"

[pagination]
  pagerSize = 10

[params]
  googleAnalytics = "G-9CFXRLCZGJ"
  description = "Este es un lugar de ambiente donde todo es diferente"
  author = "Noe Rodriguez"
  showTopHeader = false
  showSearchButton = false
  sidebarBlogPage = "right-sidebar"
  showBreadcrumb = true
  showGoToTop = true
  showComments = true
  primaryColor = "#3e63b6"      # Main accent color
  logo = "logo.png"
  favicon = "favicon.ico"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "About me"
  url = "/about-me"
  weight = 1

[[menu.main]]
  name = "Parenting"
  url = "/categories/parenting/"
  weight = 2

[[menu.main]]
  name = "Technology"
  url = "/categories/technology/"
  weight = 3

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 4

[[menu.main]]
  name = "TV Shows"
  url = "/categories/tv-shows/"
  weight = 5

[[menu.main]]
  name = "Home"
  url = "/categories/home/"
  weight = 6
